export const UPDATE_RECIPES = "UPDATE_RECIPES";

export const UPDATE_LIKES = "UPDATE_LIKES";

export const TOGGLE_LOGIN = "TOGGLE_LOGIN";

export const UPDATE_ACCOUNT_NAME = "UPDATE_ACCOUNT_NAME";

export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";

export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";